server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /research {
        try_files $uri $uri/ /research/index.html;
    }

    location /gr {
        try_files $uri $uri/ /gr/index.html;
    }

    location /forEdu {
        try_files $uri $uri/ /forEdu/index.html;
    }

    location /promo {
        try_files $uri $uri/ /;
    }

    # All paths starting with /legal will try the file, then fallback to viewer.html
    location /legal {
        try_files $uri $uri/ /legal/viewer.html;
    }

    error_page 404 /;
}
